name: Publish and Sign Container Image # This is the name of the job

on:
  schedule:
    - cron: '32 11 * * *' # creating a schedule and cron job
  push:
    branches: [ main ]
      # Publish semver tags as releases.
      tags: [ 'v*.*.*' ]
    pull_request:
      branches: [ main ] # Workflow for pull request
jobs:
  build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        id-token: write
  steps:
    - name: Checkout repo
      uses: action/checkout@v2
    - name: Install cosign
      uses: sigstore/cosign-installer@main
      with:
          cosign-release: 'v1.4.1'
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Log into ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container image
      id: push-step
      uses: docker/build-push-action@master
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
    - name: Sign the contaienr image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign ghcr.io/${{ github.repository }}@{{ steps.push-step.outputs.digest }}
